version: '3.8'

services:
  app:
    build: .
    container_name: focus-app
    ports:
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/focus
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-J1uli.24}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - focus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:14-alpine
    container_name: focus-db
    environment:
      - POSTGRES_DB=focus
      - POSTGRES_USER=${DB_USER:-focus_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-J1uli.24}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - focus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-focus_user} -d focus"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

networks:
  focus-network:
    driver: bridge

volumes:
  postgres_data:
